version: "3"
services:
  # exercise3:
  #    build: .
  #    restart: always
  #    ports:
  #      - "9003:9003"
  #    depends_on:
  #     - mongodb
  #     - mongobackup
  #     - cache

  messageapp:
    image: cabify/backend-bootcamp-messageapp
    ports:
      - "3000:3000"
  mongodb:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: 
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
  mongobackup:
    image: mongo
    volumes:
      - ./data/db2:/data/db2
    ports:
      - 27018:27017
    command: 
      - '--logpath'
      - '/var/log/mongodb/mongod2.log'
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    environment: 
      - ALLOW_EMPTY_PASSWORD=yes
    volumes: 
      - cache:/data
  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:cache:6379
    ports:
      - "8081:8081"
volumes:
  cache:
    driver: local
